title = "KingNo21's Blog"
theme = "hugo-theme-massively"

defaultContentLanguage = "en"
languageCode = "en-us"
enableRobotsTXT = true
disqusShortname = "kingno21s-blog"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

[params.posts]
  foldername = "post"
  pagesize = "6"
  featuredpost = "true"

### language ###
[languages]
[languages.en]
  contentDir = "content/en"
  languageName = "English"
  weight = 1
[languages.jp]
  contentDir = "content/jp"
  languageName = "Japanese"
  weight = 1
